spring:
  h2:
    console:
      enabled: true
  datasource:
    username: sa
    password: azerty
    url: jdbc:h2:mem:quiz
    driver-class-name: org.h2.Driver
    driverClassName: org.h2.Driver
  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.H2Dialect 
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: update
    show-sql: false
